version: "3.8"

services:
  backend:
    build: ./backend
    container_name: express-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=onlinestore
      - PORT=3000
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - node_modules:/app/node_modules # ✅ Prevents host from overwriting installed modules
    networks:
      - app-network

  postgres:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: onlinestore
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network

volumes:
  pgdata:
  node_modules: # ✅ Declare the named volume here

networks:
  app-network:
    driver: bridge
